[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
  force = true
  headers = {X-Frame-Options = "DENY", X-XSS-Protection = "1; mode=block", X-Content-Type-Options = "nosniff"}