[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/.netlify/functions/app/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200